//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BellPaintViewWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(BellPaintView), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Show", Show);
		L.RegFunction("ToggleEraserMode", ToggleEraserMode);
		L.RegFunction("InDragStart", InDragStart);
		L.RegFunction("InDragUpdate", InDragUpdate);
		L.RegFunction("InDragEnd", InDragEnd);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("eraserToggle", get_eraserToggle, set_eraserToggle);
		L.RegVar("painterMgr", get_painterMgr, set_painterMgr);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Show(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BellPaintView obj = (BellPaintView)ToLua.CheckObject<BellPaintView>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.Show(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToggleEraserMode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			BellPaintView obj = (BellPaintView)ToLua.CheckObject<BellPaintView>(L, 1);
			obj.ToggleEraserMode();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InDragStart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BellPaintView obj = (BellPaintView)ToLua.CheckObject<BellPaintView>(L, 1);
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			obj.InDragStart(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InDragUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BellPaintView obj = (BellPaintView)ToLua.CheckObject<BellPaintView>(L, 1);
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			obj.InDragUpdate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InDragEnd(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			BellPaintView obj = (BellPaintView)ToLua.CheckObject<BellPaintView>(L, 1);
			obj.InDragEnd();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eraserToggle(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BellPaintView obj = (BellPaintView)o;
			UnityEngine.UI.Toggle ret = obj.eraserToggle;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eraserToggle on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_painterMgr(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BellPaintView obj = (BellPaintView)o;
			UnityEngine.GameObject ret = obj.painterMgr;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index painterMgr on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eraserToggle(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BellPaintView obj = (BellPaintView)o;
			UnityEngine.UI.Toggle arg0 = (UnityEngine.UI.Toggle)ToLua.CheckObject<UnityEngine.UI.Toggle>(L, 2);
			obj.eraserToggle = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eraserToggle on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_painterMgr(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BellPaintView obj = (BellPaintView)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.painterMgr = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index painterMgr on a nil value");
		}
	}
}

