//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GunFollowWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GunFollow), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("TurnOnGunLua", get_TurnOnGunLua, set_TurnOnGunLua);
		L.RegVar("TurnOffGunLua", get_TurnOffGunLua, set_TurnOffGunLua);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TurnOnGunLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GunFollow obj = (GunFollow)o;
			LuaInterface.LuaFunction ret = obj.TurnOnGunLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TurnOnGunLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TurnOffGunLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GunFollow obj = (GunFollow)o;
			LuaInterface.LuaFunction ret = obj.TurnOffGunLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TurnOffGunLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TurnOnGunLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GunFollow obj = (GunFollow)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.TurnOnGunLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TurnOnGunLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TurnOffGunLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GunFollow obj = (GunFollow)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.TurnOffGunLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TurnOffGunLua on a nil value");
		}
	}
}

