//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ILFramework_FunctionOf3DofWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ILFramework.FunctionOf3Dof), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetTouchPadPositon", GetTouchPadPositon);
		L.RegFunction("GetEulerAngle", GetEulerAngle);
		L.RegFunction("GetAccelerateValue", GetAccelerateValue);
		L.RegFunction("GetScreenPoint", GetScreenPoint);
		L.RegFunction("StartOldLuaCLickFunc", StartOldLuaCLickFunc);
		L.RegFunction("ResetAllDelegate", ResetAllDelegate);
		L.RegFunction("TransInfoToButton", TransInfoToButton);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, set_Instance);
		L.RegVar("Current3DofCallBack", get_Current3DofCallBack, set_Current3DofCallBack);
		L.RegVar("OldLuaClickDown", get_OldLuaClickDown, set_OldLuaClickDown);
		L.RegVar("OldLuaClickStay", get_OldLuaClickStay, set_OldLuaClickStay);
		L.RegVar("OldLuaClickUp", get_OldLuaClickUp, set_OldLuaClickUp);
		L.RegVar("ClickAnyButtonDown", get_ClickAnyButtonDown, set_ClickAnyButtonDown);
		L.RegVar("ClickAnyButtonStay", get_ClickAnyButtonStay, set_ClickAnyButtonStay);
		L.RegVar("ClickAnyButtonUp", get_ClickAnyButtonUp, set_ClickAnyButtonUp);
		L.RegVar("LuaClickAnyButtonDown", get_LuaClickAnyButtonDown, set_LuaClickAnyButtonDown);
		L.RegVar("LuaClickAnyButtonStay", get_LuaClickAnyButtonStay, set_LuaClickAnyButtonStay);
		L.RegVar("LuaClickAnyButtonUp", get_LuaClickAnyButtonUp, set_LuaClickAnyButtonUp);
		L.RegVar("ClickOneButtonDown", get_ClickOneButtonDown, set_ClickOneButtonDown);
		L.RegVar("ClickOneButtonStay", get_ClickOneButtonStay, set_ClickOneButtonStay);
		L.RegVar("ClickOneButtonUp", get_ClickOneButtonUp, set_ClickOneButtonUp);
		L.RegVar("LuaClickOneButtonDown", get_LuaClickOneButtonDown, set_LuaClickOneButtonDown);
		L.RegVar("LuaClickOneButtonStay", get_LuaClickOneButtonStay, set_LuaClickOneButtonStay);
		L.RegVar("LuaClickOneButtonUp", get_LuaClickOneButtonUp, set_LuaClickOneButtonUp);
		L.RegVar("CurrentLua3DofCallBack", get_CurrentLua3DofCallBack, set_CurrentLua3DofCallBack);
		L.RegVar("CurrentLuaEulerCallBack", get_CurrentLuaEulerCallBack, set_CurrentLuaEulerCallBack);
		L.RegVar("CurrentLuaPadPosCallBack", get_CurrentLuaPadPosCallBack, set_CurrentLuaPadPosCallBack);
		L.RegVar("CurrentLua3DofScreenPointCallBack", get_CurrentLua3DofScreenPointCallBack, set_CurrentLua3DofScreenPointCallBack);
		L.RegVar("CurrentLua3DofAccelerateValue", get_CurrentLua3DofAccelerateValue, set_CurrentLua3DofAccelerateValue);
		L.RegVar("Type", get_Type, set_Type);
		L.RegVar("IsOpened", get_IsOpened, set_IsOpened);
		L.RegVar("EulerAngleY", get_EulerAngleY, null);
		L.RegVar("EulerAngleZ", get_EulerAngleZ, null);
		L.RegVar("EulerAngleX", get_EulerAngleX, null);
		L.RegVar("Times", get_Times, null);
		L.RegVar("Trigger", get_Trigger, null);
		L.RegVar("AppButton", get_AppButton, null);
		L.RegVar("HomeButton", get_HomeButton, null);
		L.RegVar("PadButton", get_PadButton, null);
		L.RegVar("TouchPadEvent", get_TouchPadEvent, null);
		L.RegVar("TouchPadXPos", get_TouchPadXPos, null);
		L.RegVar("TouchPadYPos", get_TouchPadYPos, null);
		L.RegVar("PadBtnLeft", get_PadBtnLeft, null);
		L.RegVar("PadBtnRight", get_PadBtnRight, null);
		L.RegVar("PadBtnTop", get_PadBtnTop, null);
		L.RegVar("PadBtnBotton", get_PadBtnBotton, null);
		L.RegVar("PadBtnCenter", get_PadBtnCenter, null);
		L.RegFunction("The3DofCallBack", ILFramework_FunctionOf3Dof_The3DofCallBack);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTouchPadPositon(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)ToLua.CheckObject<ILFramework.FunctionOf3Dof>(L, 1);
			UnityEngine.Vector2 o = obj.GetTouchPadPositon();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEulerAngle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)ToLua.CheckObject<ILFramework.FunctionOf3Dof>(L, 1);
			UnityEngine.Vector3 o = obj.GetEulerAngle();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAccelerateValue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)ToLua.CheckObject<ILFramework.FunctionOf3Dof>(L, 1);
			UnityEngine.Vector3 o = obj.GetAccelerateValue();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetScreenPoint(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)ToLua.CheckObject<ILFramework.FunctionOf3Dof>(L, 1);
			UnityEngine.Vector3 o = obj.GetScreenPoint();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartOldLuaCLickFunc(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)ToLua.CheckObject<ILFramework.FunctionOf3Dof>(L, 1);
			obj.StartOldLuaCLickFunc();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetAllDelegate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)ToLua.CheckObject<ILFramework.FunctionOf3Dof>(L, 1);
			obj.ResetAllDelegate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TransInfoToButton(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)ToLua.CheckObject<ILFramework.FunctionOf3Dof>(L, 1);
			int[] arg0 = ToLua.CheckNumberArray<int>(L, 2);
			obj.TransInfoToButton(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Current3DofCallBack(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.Current3DofCallBack);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OldLuaClickDown(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.OldLuaClickDown);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OldLuaClickStay(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.OldLuaClickStay);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OldLuaClickUp(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.OldLuaClickUp);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ClickAnyButtonDown(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.ClickAnyButtonDown);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ClickAnyButtonStay(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.ClickAnyButtonStay);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ClickAnyButtonUp(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.ClickAnyButtonUp);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaClickAnyButtonDown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.LuaClickAnyButtonDown;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickAnyButtonDown on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaClickAnyButtonStay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.LuaClickAnyButtonStay;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickAnyButtonStay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaClickAnyButtonUp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.LuaClickAnyButtonUp;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickAnyButtonUp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ClickOneButtonDown(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.ClickOneButtonDown);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ClickOneButtonStay(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.ClickOneButtonStay);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ClickOneButtonUp(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.FunctionOf3Dof.ClickOneButtonUp);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaClickOneButtonDown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.LuaClickOneButtonDown;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickOneButtonDown on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaClickOneButtonStay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.LuaClickOneButtonStay;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickOneButtonStay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaClickOneButtonUp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.LuaClickOneButtonUp;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickOneButtonUp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrentLua3DofCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.CurrentLua3DofCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLua3DofCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrentLuaEulerCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.CurrentLuaEulerCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLuaEulerCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrentLuaPadPosCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.CurrentLuaPadPosCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLuaPadPosCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrentLua3DofScreenPointCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.CurrentLua3DofScreenPointCallBack;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLua3DofScreenPointCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrentLua3DofAccelerateValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaInterface.LuaFunction ret = obj.CurrentLua3DofAccelerateValue;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLua3DofAccelerateValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Type(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			int ret = obj.Type;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Type on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsOpened(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.IsOpened;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsOpened on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EulerAngleY(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			float ret = obj.EulerAngleY;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index EulerAngleY on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EulerAngleZ(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			float ret = obj.EulerAngleZ;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index EulerAngleZ on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EulerAngleX(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			float ret = obj.EulerAngleX;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index EulerAngleX on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Times(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			int ret = obj.Times;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Times on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Trigger(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.Trigger;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Trigger on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AppButton(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.AppButton;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AppButton on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HomeButton(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.HomeButton;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HomeButton on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PadButton(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.PadButton;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PadButton on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TouchPadEvent(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			int ret = obj.TouchPadEvent;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TouchPadEvent on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TouchPadXPos(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			int ret = obj.TouchPadXPos;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TouchPadXPos on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TouchPadYPos(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			int ret = obj.TouchPadYPos;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TouchPadYPos on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PadBtnLeft(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.PadBtnLeft;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PadBtnLeft on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PadBtnRight(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.PadBtnRight;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PadBtnRight on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PadBtnTop(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.PadBtnTop;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PadBtnTop on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PadBtnBotton(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.PadBtnBotton;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PadBtnBotton on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PadBtnCenter(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool ret = obj.PadBtnCenter;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PadBtnCenter on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Instance(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof arg0 = (ILFramework.FunctionOf3Dof)ToLua.CheckObject<ILFramework.FunctionOf3Dof>(L, 2);
			ILFramework.FunctionOf3Dof.Instance = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Current3DofCallBack(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.Current3DofCallBack = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OldLuaClickDown(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.OldLuaClickDown = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OldLuaClickStay(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.OldLuaClickStay = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OldLuaClickUp(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.OldLuaClickUp = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ClickAnyButtonDown(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.ClickAnyButtonDown = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ClickAnyButtonStay(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.ClickAnyButtonStay = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ClickAnyButtonUp(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.ClickAnyButtonUp = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaClickAnyButtonDown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaClickAnyButtonDown = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickAnyButtonDown on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaClickAnyButtonStay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaClickAnyButtonStay = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickAnyButtonStay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaClickAnyButtonUp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaClickAnyButtonUp = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickAnyButtonUp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ClickOneButtonDown(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.ClickOneButtonDown = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ClickOneButtonStay(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.ClickOneButtonStay = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ClickOneButtonUp(IntPtr L)
	{
		try
		{
			ILFramework.FunctionOf3Dof.The3DofCallBack arg0 = (ILFramework.FunctionOf3Dof.The3DofCallBack)ToLua.CheckDelegate<ILFramework.FunctionOf3Dof.The3DofCallBack>(L, 2);
			ILFramework.FunctionOf3Dof.ClickOneButtonUp = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaClickOneButtonDown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaClickOneButtonDown = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickOneButtonDown on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaClickOneButtonStay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaClickOneButtonStay = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickOneButtonStay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaClickOneButtonUp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.LuaClickOneButtonUp = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClickOneButtonUp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurrentLua3DofCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.CurrentLua3DofCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLua3DofCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurrentLuaEulerCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.CurrentLuaEulerCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLuaEulerCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurrentLuaPadPosCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.CurrentLuaPadPosCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLuaPadPosCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurrentLua3DofScreenPointCallBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.CurrentLua3DofScreenPointCallBack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLua3DofScreenPointCallBack on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurrentLua3DofAccelerateValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.CurrentLua3DofAccelerateValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentLua3DofAccelerateValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Type(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.Type = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Type on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_IsOpened(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.FunctionOf3Dof obj = (ILFramework.FunctionOf3Dof)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.IsOpened = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsOpened on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ILFramework_FunctionOf3Dof_The3DofCallBack(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<ILFramework.FunctionOf3Dof.The3DofCallBack>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<ILFramework.FunctionOf3Dof.The3DofCallBack>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

