//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ILFramework_ConnectAndroidWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ILFramework.ConnectAndroid), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Init", Init);
		L.RegFunction("SendMsg", SendMsg);
		L.RegFunction("SendConnectData", SendConnectData);
		L.RegFunction("CloseSubscribe", CloseSubscribe);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, set_Instance);
		L.RegVar("CurrentStatus", get_CurrentStatus, set_CurrentStatus);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ILFramework.ConnectAndroid obj = (ILFramework.ConnectAndroid)ToLua.CheckObject<ILFramework.ConnectAndroid>(L, 1);
			bell.ai.course2.unity.websocket.MsgCallback arg0 = (bell.ai.course2.unity.websocket.MsgCallback)ToLua.CheckObject<bell.ai.course2.unity.websocket.MsgCallback>(L, 2);
			obj.Init(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ILFramework.ConnectAndroid obj = (ILFramework.ConnectAndroid)ToLua.CheckObject<ILFramework.ConnectAndroid>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SendMsg(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendConnectData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.ConnectAndroid obj = (ILFramework.ConnectAndroid)ToLua.CheckObject<ILFramework.ConnectAndroid>(L, 1);
			obj.SendConnectData();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CloseSubscribe(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.ConnectAndroid obj = (ILFramework.ConnectAndroid)ToLua.CheckObject<ILFramework.ConnectAndroid>(L, 1);
			obj.CloseSubscribe();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ILFramework.ConnectAndroid.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrentStatus(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.ConnectAndroid obj = (ILFramework.ConnectAndroid)o;
			bell.ai.course2.unity.websocket.MsgCode ret = obj.CurrentStatus;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentStatus on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Instance(IntPtr L)
	{
		try
		{
			ILFramework.ConnectAndroid arg0 = (ILFramework.ConnectAndroid)ToLua.CheckObject<ILFramework.ConnectAndroid>(L, 2);
			ILFramework.ConnectAndroid.Instance = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurrentStatus(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.ConnectAndroid obj = (ILFramework.ConnectAndroid)o;
			bell.ai.course2.unity.websocket.MsgCode arg0 = (bell.ai.course2.unity.websocket.MsgCode)ToLua.CheckObject(L, 2, typeof(bell.ai.course2.unity.websocket.MsgCode));
			obj.CurrentStatus = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrentStatus on a nil value");
		}
	}
}

