//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ILFramework_XDeviceManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ILFramework.XDeviceManager), typeof(ILFramework.Manager<ILFramework.XDeviceManager>));
		L.RegFunction("LoadfromPrefab", LoadfromPrefab);
		L.RegFunction("Init", Init);
		L.RegFunction("InitInLua", InitInLua);
		L.RegFunction("Exit", Exit);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadfromPrefab(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				ILFramework.XDeviceManager obj = (ILFramework.XDeviceManager)ToLua.CheckObject<ILFramework.XDeviceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				obj.LoadfromPrefab(arg0);
				return 0;
			}
			else if (count == 3)
			{
				ILFramework.XDeviceManager obj = (ILFramework.XDeviceManager)ToLua.CheckObject<ILFramework.XDeviceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				obj.LoadfromPrefab(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				ILFramework.XDeviceManager obj = (ILFramework.XDeviceManager)ToLua.CheckObject<ILFramework.XDeviceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				UnityEngine.Events.UnityAction arg2 = (UnityEngine.Events.UnityAction)ToLua.CheckDelegate<UnityEngine.Events.UnityAction>(L, 4);
				obj.LoadfromPrefab(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ILFramework.XDeviceManager.LoadfromPrefab");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.XDeviceManager obj = (ILFramework.XDeviceManager)ToLua.CheckObject<ILFramework.XDeviceManager>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitInLua(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				ILFramework.XDeviceManager obj = (ILFramework.XDeviceManager)ToLua.CheckObject<ILFramework.XDeviceManager>(L, 1);
				obj.InitInLua();
				return 0;
			}
			else if (count == 2)
			{
				ILFramework.XDeviceManager obj = (ILFramework.XDeviceManager)ToLua.CheckObject<ILFramework.XDeviceManager>(L, 1);
				LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
				obj.InitInLua(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ILFramework.XDeviceManager.InitInLua");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Exit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.XDeviceManager obj = (ILFramework.XDeviceManager)ToLua.CheckObject<ILFramework.XDeviceManager>(L, 1);
			obj.Exit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

