//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ILFramework_ResourceManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ILFramework.ResourceManager), typeof(ILFramework.Manager<ILFramework.ResourceManager>));
		L.RegFunction("AddResourceAB", AddResourceAB);
		L.RegFunction("AddAudioResAB", AddAudioResAB);
		L.RegFunction("AddCourseResAB", AddCourseResAB);
		L.RegFunction("ResetAudioAndCourseResAB", ResetAudioAndCourseResAB);
		L.RegFunction("RemoveResourceAB", RemoveResourceAB);
		L.RegFunction("LoadOneIDCommonPrefabAsyn", LoadOneIDCommonPrefabAsyn);
		L.RegFunction("ReloadAssetBundle", ReloadAssetBundle);
		L.RegFunction("LoadPrefab", LoadPrefab);
		L.RegFunction("LoadCommonPrefab", LoadCommonPrefab);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("commonResList", get_commonResList, set_commonResList);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddResourceAB(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
			ILFramework.HotfixPackage arg0 = (ILFramework.HotfixPackage)ToLua.CheckObject<ILFramework.HotfixPackage>(L, 2);
			UnityEngine.AssetBundle arg1 = (UnityEngine.AssetBundle)ToLua.CheckObject<UnityEngine.AssetBundle>(L, 3);
			obj.AddResourceAB(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddAudioResAB(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
			UnityEngine.AssetBundle arg0 = (UnityEngine.AssetBundle)ToLua.CheckObject<UnityEngine.AssetBundle>(L, 2);
			obj.AddAudioResAB(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddCourseResAB(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
			UnityEngine.AssetBundle arg0 = (UnityEngine.AssetBundle)ToLua.CheckObject<UnityEngine.AssetBundle>(L, 2);
			obj.AddCourseResAB(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetAudioAndCourseResAB(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
			obj.ResetAudioAndCourseResAB();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveResourceAB(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
			ILFramework.HotfixPackage arg0 = (ILFramework.HotfixPackage)ToLua.CheckObject<ILFramework.HotfixPackage>(L, 2);
			obj.RemoveResourceAB(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadOneIDCommonPrefabAsyn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.LoadOneIDCommonPrefabAsyn(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReloadAssetBundle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
			obj.ReloadAssetBundle();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadPrefab(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				string[] arg1 = ToLua.CheckStringArray(L, 3);
				obj.LoadPrefab(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				string[] arg1 = ToLua.CheckStringArray(L, 3);
				LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
				obj.LoadPrefab(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ILFramework.ResourceManager.LoadPrefab");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadCommonPrefab(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.GameObject o = obj.LoadCommonPrefab(arg0);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else if (count == 3)
			{
				ILFramework.ResourceManager obj = (ILFramework.ResourceManager)ToLua.CheckObject<ILFramework.ResourceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				UnityEngine.GameObject o = obj.LoadCommonPrefab(arg0, arg1);
				ToLua.PushSealed(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ILFramework.ResourceManager.LoadCommonPrefab");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_commonResList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.ResourceManager obj = (ILFramework.ResourceManager)o;
			UnityEngine.AssetBundle ret = obj.commonResList;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index commonResList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_commonResList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ILFramework.ResourceManager obj = (ILFramework.ResourceManager)o;
			UnityEngine.AssetBundle arg0 = (UnityEngine.AssetBundle)ToLua.CheckObject<UnityEngine.AssetBundle>(L, 2);
			obj.commonResList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index commonResList on a nil value");
		}
	}
}

