//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Object3DActionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Object3DAction), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("index", get_index, set_index);
		L.RegVar("OnCollisionEnterLua", get_OnCollisionEnterLua, set_OnCollisionEnterLua);
		L.RegVar("OnCollisionEnter2DLua", get_OnCollisionEnter2DLua, set_OnCollisionEnter2DLua);
		L.RegVar("OnCollisionExitLua", get_OnCollisionExitLua, set_OnCollisionExitLua);
		L.RegVar("OnCollisionExit2DLua", get_OnCollisionExit2DLua, set_OnCollisionExit2DLua);
		L.RegVar("OnCollisionStayLua", get_OnCollisionStayLua, set_OnCollisionStayLua);
		L.RegVar("OnCollisionStay2DLua", get_OnCollisionStay2DLua, set_OnCollisionStay2DLua);
		L.RegVar("OnMouseDownLua", get_OnMouseDownLua, set_OnMouseDownLua);
		L.RegVar("OnMouseDragLua", get_OnMouseDragLua, set_OnMouseDragLua);
		L.RegVar("OnMouseEnterLua", get_OnMouseEnterLua, set_OnMouseEnterLua);
		L.RegVar("OnMouseExitLua", get_OnMouseExitLua, set_OnMouseExitLua);
		L.RegVar("OnMouseOverLua", get_OnMouseOverLua, set_OnMouseOverLua);
		L.RegVar("OnMouseUpLua", get_OnMouseUpLua, set_OnMouseUpLua);
		L.RegVar("OnParticleCollisionLua", get_OnParticleCollisionLua, set_OnParticleCollisionLua);
		L.RegVar("OnParticleTriggerLua", get_OnParticleTriggerLua, set_OnParticleTriggerLua);
		L.RegVar("OnTriggerEnterLua", get_OnTriggerEnterLua, set_OnTriggerEnterLua);
		L.RegVar("OnTriggerEnter2DLua", get_OnTriggerEnter2DLua, set_OnTriggerEnter2DLua);
		L.RegVar("OnTriggerStayLua", get_OnTriggerStayLua, set_OnTriggerStayLua);
		L.RegVar("OnTriggerStay2DLua", get_OnTriggerStay2DLua, set_OnTriggerStay2DLua);
		L.RegVar("OnTriggerExitLua", get_OnTriggerExitLua, set_OnTriggerExitLua);
		L.RegVar("OnTriggerExit2DLua", get_OnTriggerExit2DLua, set_OnTriggerExit2DLua);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_index(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			int ret = obj.index;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index index on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnCollisionEnterLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnCollisionEnterLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionEnterLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnCollisionEnter2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnCollisionEnter2DLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionEnter2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnCollisionExitLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnCollisionExitLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionExitLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnCollisionExit2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnCollisionExit2DLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionExit2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnCollisionStayLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnCollisionStayLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionStayLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnCollisionStay2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnCollisionStay2DLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionStay2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnMouseDownLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnMouseDownLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseDownLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnMouseDragLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnMouseDragLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseDragLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnMouseEnterLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnMouseEnterLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseEnterLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnMouseExitLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnMouseExitLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseExitLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnMouseOverLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnMouseOverLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseOverLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnMouseUpLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnMouseUpLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseUpLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnParticleCollisionLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnParticleCollisionLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnParticleCollisionLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnParticleTriggerLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnParticleTriggerLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnParticleTriggerLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnTriggerEnterLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnTriggerEnterLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerEnterLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnTriggerEnter2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnTriggerEnter2DLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerEnter2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnTriggerStayLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnTriggerStayLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerStayLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnTriggerStay2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnTriggerStay2DLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerStay2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnTriggerExitLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnTriggerExitLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerExitLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnTriggerExit2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaInterface.LuaFunction ret = obj.OnTriggerExit2DLua;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerExit2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_index(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.index = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index index on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnCollisionEnterLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnCollisionEnterLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionEnterLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnCollisionEnter2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnCollisionEnter2DLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionEnter2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnCollisionExitLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnCollisionExitLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionExitLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnCollisionExit2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnCollisionExit2DLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionExit2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnCollisionStayLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnCollisionStayLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionStayLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnCollisionStay2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnCollisionStay2DLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnCollisionStay2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnMouseDownLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnMouseDownLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseDownLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnMouseDragLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnMouseDragLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseDragLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnMouseEnterLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnMouseEnterLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseEnterLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnMouseExitLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnMouseExitLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseExitLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnMouseOverLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnMouseOverLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseOverLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnMouseUpLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnMouseUpLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnMouseUpLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnParticleCollisionLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnParticleCollisionLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnParticleCollisionLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnParticleTriggerLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnParticleTriggerLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnParticleTriggerLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnTriggerEnterLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnTriggerEnterLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerEnterLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnTriggerEnter2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnTriggerEnter2DLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerEnter2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnTriggerStayLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnTriggerStayLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerStayLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnTriggerStay2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnTriggerStay2DLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerStay2DLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnTriggerExitLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnTriggerExitLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerExitLua on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnTriggerExit2DLua(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Object3DAction obj = (Object3DAction)o;
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnTriggerExit2DLua = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnTriggerExit2DLua on a nil value");
		}
	}
}

